name: new_weather_app
description: "Приложение для отображения погоды и профиля пользователя"
publish_to: 'none'

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  geolocator: ^13.0.2
  json_annotation: ^4.8.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
